#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Drupal Installer', '1.0.0');
$app->add(new Ankitjain28may\DrupalHost\Console\NewCommand);

$app->run();