#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$commands = [
    __DIR__.'/setup.sh',
];
$app = new Symfony\Component\Console\Application('Drupal Installer', '2.1.0');
$app->add(new Ankitjain28may\DrupalHost\Console\NewCommand($commands));

$app->run();